version: '3.8'

services:
  crud_db:
    image: mongo
    container_name: crud_db
    restart: always
    ports:
      - 27017:27017
    networks:
      - network_crud

  crud:
    build:
      dockerfile: Dockerfile
      context: ./
    image: nodejs
    container_name: crud
    restart: unless-stopped
    environment:
      - PORT=7000
      - MONGODB_URI=mongodb://crud_db/mern-tasks
      - NODE_ENV=production
      - VITE_API_URL=/api
    ports:
      - 7000:7000
    networks:
      - network_crud
    depends_on:
      - crud_db

networks:
  network_crud:
    driver: bridge