version: '3.8'

services:
  crud_db:
    image: mongo
    container_name: crud_db
    restart: always
    ports:
      - 27017:27017
    networks:
      - network_crud

networks:
  network_crud:
    driver: bridge